
  - name: "Instalar servidor dhcp"
    apt:
      name:
        - isc-dhcp-server

  - name: "Modificar los archivos de configuración del servidor"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: 0644
    with_items:
      - { src: isc-dhcp, dest: /etc/default/isc-dhcp-server }
      - { src: dhcpd.conf, dest: /etc/dhcp/dhcpd.conf }
    notify: reinicio_dhcp