  - name: "Actualizar los repositorios"
    apt:
      update_cache: yes
      upgrade: "yes"

  - name: "Instalar servidor dhcp e iptables"
    apt:
      name:
        - isc-dhcp-server
        - iptables

  - name: "Activar el bit de forwarding"
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      reload: yes

  - name: "Modificar las interfaces desde plantilla"
    template:
      src: interfaces
      dest: /etc/network/interfaces
      mode: 0644
    notify: reiniciar

  - name: "Modificar archivo isc-dhcp-server"
    template:
      src: isc-dhcp
      dest: /etc/default/isc-dhcp-server
      mode: 0644
    notify: reinicio_dhcp