  - name: "Actualizar los repositorios"
    apt:
      update_cache: yes
      upgrade: "yes"

  - name: "Instalar servidor dhcp e iptables"
    apt:
      name:
        - isc-dhcp-server
        - iptables


- name: "Activar el bit de forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes